public class mz implements mr {
   public static final mz dr = new mz(98, -1);
   public static final mz ae = new mz(1, -1);
   public static final mz ag = new mz(2, 8);
   public static final mz am = new mz(3, 8);
   public static final mz ax = new mz(4, 7);
   public static final mz dj = new mz(89, 15);
   public static final mz ak = new mz(25, -1);
   public static final mz bu = new mz(43, 7);
   public static final mz co = new mz(61, -1);
   public static final mz bo = new mz(45, -1);
   public static final mz ap = new mz(13, 3);
   public static final mz ad = new mz(11, 8);
   public static final mz cd = new mz(75, -1);
   public static final mz dk = new mz(82, -1);
   public static final mz dt = new mz(81, 4);
   public static final mz az = new mz(15, 15);
   public static final mz aa = new mz(16, 7);
   public static final mz ai = new mz(17, 2);
   public static final mz ao = new mz(18, 4);
   public static final mz as = new mz(19, 6);
   public static final mz ay = new mz(20, 3);
   public static final mz ct = new mz(64, 3);
   public static final mz cg = new mz(63, -1);
   public static final mz aw = new mz(23, 8);
   public static final mz an = new mz(24, 3);
   public static final mz be = new mz(50, 0);
   public static final mz bn = new mz(26, -1);
   public static final mz bh = new mz(27, -2);
   public static final mz bd = new mz(28, 0);
   public static final mz bx = new mz(29, 0);
   public static final mz bf = new mz(30, 7);
   public static final mz bm = new mz(31, -1);
   public static final mz bq = new mz(48, -1);
   public static final mz bc = new mz(51, 3);
   public static final mz ba = new mz(34, 13);
   public static final mz bj = new mz(35, -1);
   public static final mz bp = new mz(36, 10);
   public static final mz by = new mz(37, 16);
   public static final mz bs = new mz(32, 9);
   public static final mz bw = new mz(33, 11);
   static final mz bg = new mz(40, -1);
   public static final mz bl = new mz(41, 7);
   public static final mz bb = new mz(38, -1);
   public static final mz cu = new mz(55, 11);
   public static final mz br = new mz(44, 3);
   static final mz au = new mz(8, -1);
   public static final mz bv = new mz(46, -1);
   public static final mz bt = new mz(47, 3);
   public static final mz cn = new mz(52, 3);
   public static final mz da = new mz(95, 22);
   public static final mz ah = new mz(12, 5);
   public static final mz cv = new mz(62, 8);
   public static final mz cr = new mz(69, 15);
   static final mz ch = new mz(53, 2);
   public static final mz cf = new mz(54, 8);
   public static final mz bk = new mz(49, 8);
   public static final mz cm = new mz(56, 3);
   public static final mz cj = new mz(57, -2);
   public static final mz cx = new mz(58, 4);
   public static final mz ab = new mz(14, 16);
   public static final mz cy = new mz(60, -1);
   public static final mz db = new mz(84, 0);
   public static final mz ci = new mz(59, 15);
   public static final mz aj = new mz(21, 8);
   public static final mz ar = new mz(9, -1);
   public static final mz cq = new mz(65, 11);
   public static final mz cc = new mz(66, 11);
   public static final mz cz = new mz(67, 4);
   public static final mz cw = new mz(68, 1);
   public static final mz aq = new mz(5, 1);
   public static final mz cl = new mz(70, 2);
   public static final mz ca = new mz(71, 2);
   public static final mz cs = new mz(72, -2);
   public static final mz cp = new mz(73, 8);
   public static final mz cb = new mz(74, -1);
   public static final mz av = new mz(22, 10);
   public static final mz ce = new mz(76, 3);
   public static final mz ck = new mz(77, 7);
   public static final mz dp = new mz(78, 1);
   public static final mz at = new mz(7, 8);
   public static final mz bi = new mz(39, 6);
   public static final mz al = new mz(10, 3);
   public static final mz ac = new mz(0, 0);
   public static final mz dl = new mz(83, 3);
   public static final mz af = new mz(6, 7);
   public static final mz dc = new mz(85, 7);
   static final mz dw = new mz(86, 2);
   public static final mz de = new mz(87, 26);
   public static final mz dx = new mz(88, 3);
   public static final mz dv = new mz(80, -1);
   public static final mz do = new mz(90, 7);
   public static final mz dh = new mz(91, 4);
   public static final mz dm = new mz(92, -1);
   public static final mz dq = new mz(93, 6);
   public static final mz di = new mz(94, 4);
   public static final mz df = new mz(79, 3);
   public static final mz dz = new mz(96, -1);
   static final mz dg = new mz(97, 7);
   public static final mz bz = new mz(42, 7);
   public static final mz dy = new mz(99, 2);
   final int ds;
   final int dn;

   mz(int var1, int var2) {
      try {
         super();
         this.ds = 1997737841 * var1;
         this.dn = var2 * 1974943043;
      } catch (RuntimeException var3) {
         throw vk.ae(var3, "mz.<init>(" + ')');
      }
   }
}
