import java.util.Iterator;

public class ok {
   public static String ht;
   public static String dl = "Could not complete login.";
   public static String ag = "Swap this note at any bank for the equivalent item";
   public static String ew = "";
   public static String ax = "Drop";
   public static String aq = "Hidden";
   public static String cl = "";
   public static String jn;
   public static String au = "Continue";
   public static String gl;
   public static String lr;
   public static String at = "Select";
   public static String ah = "for 30 days: ";
   public static String en = "";
   public static String mc;
   public static String dy = "Sorry invited players only.";
   public static String aa = "Starting game engine...";
   public static String ai = "Connecting to update server";
   public static String ao = "Checking for updates - ";
   public static String as = "Loaded update list";
   public static String ay = "Prepared sound engine";
   public static String aj = "Loading fonts - ";
   public static String iz;
   public static String aw = "Loading title screen - ";
   public static String an = "Loaded title screen";
   public static String ak = "Loading config - ";
   public static String bn = "Loaded config";
   public static String bu = "";
   public static String bd = "Loaded sprites";
   public static String bx = "Loading textures - ";
   public static String cz = "";
   public static String bm = "Loaded input handler";
   public static String bs = "Loading wordpack - ";
   public static String bw = "Loaded wordpack";
   public static String ae = "Login to a members' server to use this object.";
   public static String bj = "Loaded interfaces";
   public static String ha;
   public static String by = "Loaded world map";
   static String bb = "Please visit the support page for assistance.";
   public static String hx;
   public static String bg = "Recover Account";
   public static String ge;
   public static String bz = "Please enter a 6-digit PIN.";
   public static String ed = "";
   public static String br = "You have only just left another world.";
   public static String bo = "Your profile will be transferred in:";
   public static String bv = " seconds.";
   public static String bt = "Connection timed out.";
   public static String bq = "Please try using a different world.";
   public static String bk = "";
   public static String be = "Error connecting to server.";
   public static String ch = "No response from server.";
   public static String gw;
   public static String ky;
   public static String cf = "Please try using a different world.";
   public static String cu = "";
   public static String cm = "Your account has been involved";
   public static String cj = "in serious rule breaking.";
   public static String co = "Please try again later.";
   public static String ci = "Either your account is still logged in, or the last";
   public static String cy = "world you were using has become unavailable.";
   public static String im;
   public static String hg;
   public static String cg = "Please reload this page.";
   public static String cv = "RuneScape has been updated!";
   public static String jt;
   public static String dp = "Press 'change your password' on front page.";
   public static String ix;
   public static String cw = "Unable to connect.";
   public static String ic;
   public static String ks;
   public static String ca = "Login limit exceeded.";
   public static String kd;
   public static String cp = "";
   public static String cb = "Unable to connect.";
   public static String mh;
   public static String fc;
   public static String ct = "";
   public static String je;
   public static String df = "";
   public static String dv = "You need a members account to login to this world.";
   public static String dt = "Please subscribe, or use a different world.";
   public static String ih;
   public static String jr;
   public static String db = "Please try using a different world.";
   public static String dc = "";
   public static String dw = "The server is being updated.";
   public static String de = "Please wait 1 minute and try again.";
   public static String lo;
   public static String gf;
   public static String do = "You can use the Jagex Launcher to continue playing.";
   public static String dh = "Press the button below to download it now.";
   public static String dm = "To access this free world, log into a";
   public static String dq = "members world and move your character";
   public static String di = "to a non-members area.";
   public static String da = "Your account has been locked due to";
   public static String dz = "suspicious activity.";
   public static String dg = "Please recover your account.";
   public static String dx = "";
   public static String bp = "Loading world map - ";
   public static String ex = "Please contact customer support.";
   public static String dn = "Invalid loginserver requested.";
   public static String du = "Please try using a different world.";
   public static String dd = "";
   public static String eg = "Malformed login packet.";
   public static String ea = "Please try again.";
   public static String ez = "";
   public static String ap = "Loading - please wait.";
   public static String ef = "Please wait 1 minute and try again.";
   public static String ac = " (Members)";
   public static String ep = "Error loading your profile.";
   public static String mu;
   public static String eh = "";
   public static String eu = "Unexpected loginserver response.";
   public static String hu;
   public static String ce = "";
   public static String el = "This computers address has been blocked";
   public static String ds = "Please use a different world.";
   public static String gk;
   public static String if;
   public static String ek = "Service unavailable.";
   public static String ko;
   public static String ey = "";
   public static String er = "Please enter your username/email address.";
   public static String fw;
   public static String ee = "";
   public static String eq = "Please enter your password.";
   public static String ej = "";
   public static String ec = "Your account must have a displayname set";
   public static String et = "in order to play the game.  Please set it";
   public static String fv = "via the website, or the main game.";
   public static String ff = "The unpaid balance on your account needs";
   public static String fe = "to be resolved before you can play.";
   public static String ft;
   public static String fb;
   public static String fk;
   public static String fp;
   public static String fr;
   public static String gz;
   public static String fu;
   public static String fj;
   public static String lb;
   public static String fq;
   public static String fn;
   public static String fh;
   public static String fo;
   public static String gt;
   public static String fd;
   public static String fi;
   public static String gj;
   public static String fm;
   public static String fx;
   public static String fy;
   public static String fz;
   public static String fa;
   public static String fl;
   public static String go;
   public static String af = "Ok";
   public static String lp;
   public static String iy;
   public static String gb;
   public static String ei = "Please try using a different world.";
   public static String gs;
   public static String al = "null";
   public static String fg;
   public static String gx;
   public static String gu;
   public static String gp;
   public static String ev = "No reply from loginserver.";
   public static String mx;
   public static String ju;
   public static String gc;
   public static String ar = "Discard";
   public static String gr;
   public static String hh;
   public static String gv;
   public static String gi;
   public static String dr = "This world is running a closed Beta.";
   public static String gh;
   public static String gn;
   public static String gg;
   public static String gy;
   public static String av = "Loaded fonts";
   public static String hf;
   public static String cd = "Bad session id.";
   public static String hr;
   public static String kw;
   public static String hi;
   public static String hy;
   public static String hd;
   public static String hj;
   public static String hw;
   public static String bh = "Loading sprites - ";
   public static String lz;
   public static String hn;
   public static String hb;
   public static String hq;
   public static String hm;
   public static String hz;
   public static String ll;
   public static String he;
   public static String ki;
   public static String hv;
   public static String hl;
   public static String in;
   public static String hc;
   public static String bf = "Loaded textures";
   public static String hs;
   public static String ie;
   public static String kl;
   public static String is;
   public static String cc = "Please use a different world.";
   public static String jp;
   public static String ii;
   public static String iw;
   public static String id;
   public static String ip;
   public static String lq;
   public static String ir;
   public static String it;
   public static String il;
   public static String cr = "Login server offline.";
   public static String gq;
   public static String io;
   public static String ik;
   public static String ib;
   public static String ig;
   public static String dj = "Too many login attempts.";
   public static String lg;
   public static String iu;
   public static String iq;
   public static String ad = "Trust this computer";
   public static String bc = "Please try using a different world.";
   public static String dk = "";
   public static String jv;
   public static String jf;
   public static String cn = "";
   public static String ln;
   public static String kg;
   public static String jw;
   public static String jo;
   public static String bl = "";
   public static String ji;
   public static String jg;
   public static String eb = "";
   public static String ja;
   public static String ba = "Loading interfaces - ";
   public static String hp;
   public static String js;
   public static String jk;
   public static String gd;
   public static String ho;
   public static String ml;
   public static String kp;
   public static String kh;
   public static String gm;
   public static String kx;
   public static String ka;
   public static String cx = "";
   public static String kc;
   public static String kt;
   public static String kk;
   public static String kb;
   public static String kz;
   public static String am = "Take";
   public static String kv;
   public static String ke;
   public static String cs = "Too many connections from your address.";
   public static String cq = "This world is full.";
   public static String kq;
   public static String fs;
   public static String ld;
   public static String es = "";
   public static String lu;
   public static String lv;
   public static String mq;
   public static String ab = "Connection lost";
   public static String kf;
   public static String le;
   public static String la;
   public static String ga;
   public static String hk;
   public static String lc;
   public static String ls;
   public static String lx;
   public static String ck = "We suspect someone knows your password.";
   public static String lm;
   public static String lw;
   public static String iv;
   public static String eo = "";
   public static String lf;
   public static String lh;
   public static String em = "as it was used to break our rules.";
   public static String li;
   public static String lt;
   public static String lj;
   public static String lk;
   public static String ia;
   public static String mo;
   public static String bi = "View Appeal Options";
   public static String md;
   public static String az = "Please wait - attempting to reestablish";
   public static String jh;
   public static String mb;
   public static String mg;
   public static String mp;
   public static String mn;
   public static String mr;
   public static String mz;
   public static String ly;
   public static String ij;
   public static String mj;
   public static String mk;
   public static String me;
   public static String mf;
   static int pw;
   static int uc;

   ok() throws Throwable {
      try {
         super();
         throw new Error();
      } catch (RuntimeException var1) {
         throw vk.ae(var1, "ok.<init>(" + ')');
      }
   }

   static {
      ft = bb;
      fb = "Your account is currently inaccessible.";
      fk = "Please try again in a few minutes.";
      fp = "";
      fr = "You need to vote to play!";
      fg = "Visit runescape.com and vote,";
      fu = "and then come back here!";
      fj = "This world is running a";
      fs = "closed beta. Please";
      fq = "use a different world.";
      fn = "Sorry, but your account is not eligible to play.";
      fh = "For more information, please take a look at";
      fo = "our privacy policy.";
      fw = "Privacy Policy";
      fd = "Enter the 6-digit code generated by your";
      fi = "authenticator app.";
      fc = "";
      fm = "The code you entered was incorrect.";
      fx = "Please try again.";
      fy = "";
      fz = "Login attempt timed out.";
      fa = "Please try again.";
      fl = "";
      ga = "You were signed out.";
      gd = "Please sign in again.";
      gl = "";
      ge = "Failed to login.";
      gb = "Please try again.";
      go = "";
      gs = "Unexpected server response";
      gp = "Please try using a different world.";
      gf = "";
      gx = " has logged in.";
      gu = " has logged out.";
      gj = "Unable to find ";
      gt = "Use";
      gz = "Examine";
      gm = "Attack";
      gc = "Choose Option";
      gw = " more options";
      gr = "Walk here";
      gq = "level-";
      gv = "skill-";
      gi = "Please wait...";
      gk = "Close";
      gh = " ";
      gn = "M";
      gg = "M";
      gy = "K";
      hc = "K";
      hf = "World";
      he = "Your friend list is full. Max of 200 for free users, and 400 for members";
      hr = " is already on your friend list";
      hk = "Your ignore list is full. Max of 100 for free users, and 400 for members";
      hi = " is already on your ignore list";
      hy = "You can't add yourself to your own friend list";
      hd = "You can't add yourself to your own ignore list";
      hj = "Please remove ";
      hw = " from your ignore list first";
      hg = "Please remove ";
      hp = " from your friend list first";
      hn = "yellow:";
      hb = "red:";
      hq = "green:";
      hm = "cyan:";
      hz = "purple:";
      hu = "white:";
      ht = "flash1:";
      hh = "flash2:";
      hv = "flash3:";
      hl = "glow1:";
      ha = "glow2:";
      hx = "glow3:";
      ho = "rainbow:";
      hs = "pattern";
      ie = "wave:";
      id = "wave2:";
      is = "shake:";
      ia = "scroll:";
      if = "slide:";
      ii = "RuneScape is loading - please wait...";
      iz = "";
      ij = "Enter your username/email & password.";
      ip = "";
      ix = "Warning!";
      ir = "This is a <col=ff0000>PvP<col=ffffff> world.";
      it = "Players can attack each other";
      il = "almost everywhere.";
      iw = "This is a <col=ffff00>High Risk<col=ffffff> world.";
      iv = "The Protect Item prayer will";
      io = "not work on this world.";
      ik = "This is a <col=ffff00>High Risk <col=ff0000>PvP<col=ffffff> world.";
      ib = "Players can attack each other almost everywhere";
      ig = "and the Protect Item prayer won't work.";
      iy = "This is a <col=00ffff>Beta<col=ffffff> world.";
      ih = "Your normal account will not be affected.";
      iu = "";
      iq = "Authenticator";
      im = "";
      in = "Connecting to server...";
      ic = "";
      jv = "The game servers are currently being updated.";
      jf = "Please wait a few minutes and try again.";
      jr = "";
      jt = "";
      je = "You were disconnected from the server.";
      jw = "";
      jo = "Login: ";
      jp = "Password: ";
      ji = "PIN: ";
      jg = "Welcome to RuneScape";
      jh = "New User";
      ja = "Existing User";
      jn = "Login";
      ju = "Cancel";
      js = "Remember username";
      jk = "Hide username";
      kg = "Incorrect username or password.";
      kc = "If you have upgraded to a Jagex Account, you";
      ki = "need to log in using the <u=ffd200><col=ffd200>Jagex Launcher</col></u> instead.";
      kp = "Try again";
      kh = "Forgotten password?";
      kd = "Forgotten your password?";
      kx = "Username/email: ";
      ka = "Recover";
      kf = "Back";
      ks = "Can't login? Click here.";
      kt = "Still having trouble logging in?";
      kk = "Having trouble logging in?";
      kb = "";
      kz = "Page has opened in the browser.";
      kl = "";
      kv = "Please enter your username.";
      ke = "If you created your account after November";
      ko = "2010, this will be the creation email address.";
      kw = kb;
      kq = kz;
      ky = kl;
      ld = "";
      lb = "Error connecting to server.";
      lu = "";
      lv = "The part of the website you are trying";
      lz = "to connect to is offline at the moment.";
      ll = "Please try again later.";
      lq = "Sorry, there was an error trying to";
      le = "log you in to this part of the website.";
      la = "Please try again later.";
      ln = "";
      lp = "Error connecting to server.";
      lc = "";
      ls = "You must enter a valid login to proceed. For accounts";
      lx = "created after 24th November 2010, please use your";
      lr = "email address. Otherwise please use your username.";
      lm = "Your date of birth isn't set.";
      lw = "Please verify your account status by";
      ly = "setting your date of birth.";
      lg = "Set Date of Birth";
      lf = "Your date of birth information is waiting";
      lh = "to be reviewed by our staff.";
      lo = "It will be processed shortly.";
      li = "Before using this app, please read and accept our";
      lt = "<col=ffd200>terms of use</col>, <col=ffd200>privacy policy</col>, and <col=ffd200>end user licence</col>";
      lj = "<col=ffd200>agreement (EULA)</col>.";
      lk = "By accepting, you agree to these documents.";
      mu = "You must accept our terms of use, privacy policy,";
      mo = "and end user licence agreement to continue.";
      mh = "Accept";
      md = "Decline";
      ml = "Select a world";
      mc = "Members only world";
      mb = "Free world";
      mg = "World";
      mp = "Players";
      mn = "Location";
      mr = "Type";
      mz = "OFF";
      mx = "FULL";
      mq = "Loading...";
      mj = "Click to switch";
      mk = "Download Launcher";
      me = "https://oldschool.runescape.com/launcher";
      mf = "https://support.runescape.com/hc/en-gb/articles/360001552065";
   }

   public static void ag(int var0, int var1, int var2) {
      try {
         Iterator var3 = mm.au.iterator();

         while(var3.hasNext()) {
            if (var2 == 484971093) {
               throw new IllegalStateException();
            }

            ne var4 = (ne)var3.next();
            var4.io(var0, var1, 338596605);
         }

      } catch (RuntimeException var5) {
         throw vk.ae(var5, "ok.ag(" + ')');
      }
   }
}
